### ISSUE TITLE
Bad MumMER?

### ISSUE THREAD

**Issue by anandksrao** [combogenomics/medusa#11]
Hi,
I just installed Medusa 1.6 today from this [link](https://github.com/combogenomics/medusa/releases/download/medusa-1.6/medusa.tar.gz),  and Mummer from dmg for Mac OS X yesterday.
I tested and received error as follow. What do I need to fix (for installation)? Please see below.
Does this look like a bad MumMER installation a the underlying cause?
Thanks,
A

rri301as908:medusa anand$ sudo java -jar medusa.jar -f test/reference_genomes/ -i test/Rhodobacter_target.fna -v
INPUT FILE:test/Rhodobacter_target.fna
------------------------------------------------------------------------------------------------------------------------
Running MUMmer...1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref" of length 4386797
# construct suffix tree for sequence of length 4386797
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 43867 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 1.45
# reading input file "/medusa-master/medusa/test/reference_genomes/Rhodobacter_SW2_uid40865.fna.inp" of length 3514400
# matching query-file "/medusa-master/medusa/test/reference_genomes/Rhodobacter_SW2_uid40865.fna.inp"
# against subject-file "Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref"
# COMPLETETIME /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 4.24
# SPACE /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 7.66
4: FINISHING DATA
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref" of length 4386797
# construct suffix tree for sequence of length 4386797
# (maximum reference length is 536870908)
# (maximum query length is 4294967295)
# process 43867 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 1.49
# reading input file "/medusa-master/medusa/test/reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp" of length 4417791
# matching query-file "/medusa-master/medusa/test/reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp"
# against subject-file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref"
# COMPLETETIME /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 4.45
# SPACE /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 8.53
4: FINISHING DATA
done.
------------------------------------------------------------------------------------------------------------------------
Building the network...Traceback (most recent call last):
  File "medusa_scripts/netcon_mummer.py", line 5, in <module>
    import networkx as nx
ImportError: No module named networkx
Exception in thread "main" java.lang.RuntimeException: Error: Network construction failed.
	at Scaffolder.scaffolder(Unknown Source)
	at Scaffolder.runOnTerminal(Unknown Source)
	at Scaffolder.<init>(Unknown Source)
	at Scaffolder.main(Unknown Source)

**Comment by EBosi** [comment]
Hi,
It seems you don't have networkx installed, check and give it a try.
Best
Emanuele

Il 29 mar 2017 02:01, "anandksrao" <notifications@github.com> ha scritto:

Hi,
I just installed Medusa 1.6 today from this link
<https://github.com/combogenomics/medusa/releases/download/medusa-1.6/medusa.tar.gz>,
and Mummer from dmg for Mac OS X yesterday.
I tested and received error as follow. What do I need to fix (for
installation)? Please see below.
Does this look like a bad MumMER installation a the underlying cause?
Thanks,
A
rri301as908:medusa anand$ sudo java -jar medusa.jar -f
test/reference_genomes/ -i test/Rhodobacter_target.fna -v
INPUT FILE:test/Rhodobacter_target.fna

Running MUMmer...1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
reading input file "Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref" of
length 4386797 construct suffix tree for sequence of length 4386797 (maximum
reference length is 536870908) (maximum query length is 4294967295) process
43867 characters per dot

#...........................................................
.........................................
CONSTRUCTIONTIME /usr/local/bin/MUMmer3.23/mummer
Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref
1.45 reading input file "/medusa-master/medusa/test/
reference_genomes/Rhodobacter_SW2_uid40865.fna.inp" of length 3514400 matching
query-file "/medusa-master/medusa/test/reference_genomes/Rhodobacter_
SW2_uid40865.fna.inp" against subject-file "Rhodobacter_target_
Rhodobacter_SW2_uid40865.ntref" COMPLETETIME /usr/local/bin/MUMmer3.23/mummer
Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref 4.24 SPACE
/usr/local/bin/MUMmer3.23/mummer
Rhodobacter_target_Rhodobacter_SW2_uid40865.ntref
7.66

4: FINISHING DATA
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
reading input file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref"
of length 4386797 construct suffix tree for sequence of length 4386797 (maximum
reference length is 536870908) (maximum query length is 4294967295) process
43867 characters per dot

#...........................................................
.........................................
CONSTRUCTIONTIME /usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_
Rhodobacter_sphaeroides_WS8N.ntref 1.49 reading input file
"/medusa-master/medusa/test/reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp"
of length 4417791 matching query-file "/medusa-master/medusa/test/
reference_genomes/Rhodobacter_sphaeroides_WS8N.fna.inp" against
subject-file "Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref"
COMPLETETIME
/usr/local/bin/MUMmer3.23/mummer Rhodobacter_target_
Rhodobacter_sphaeroides_WS8N.ntref 4.45 SPACE /usr/local/bin/MUMmer3.23/mummer
Rhodobacter_target_Rhodobacter_sphaeroides_WS8N.ntref 8.53 4: FINISHING DATA
done.

Building the network...Traceback (most recent call last):
File "medusa_scripts/netcon_mummer.py", line 5, in
import networkx as nx
ImportError: No module named networkx
Exception in thread "main" java.lang.RuntimeException: Error: Network
construction failed.
at Scaffolder.scaffolder(Unknown Source)
at Scaffolder.runOnTerminal(Unknown Source)
at Scaffolder.(Unknown Source)
at Scaffolder.main(Unknown Source)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/combogenomics/medusa/issues/11>, or mute the thread

**Comment by anandksrao** [comment]
Thanks, ended being something silly - related to folder permissions. It works perfectly now.
